* DONE Выбрать любое издание, где есть компьютерно-приемлемый API
* [2/2]  Скачать и распарсить
  - [X] curl'ом
  - [X] рубями
* DONE Найти диффикатор по словам, а не по строчкам, протестировать её, поменяв что-нибудь вручную в новости
* [3/3] Хранение, чексуммирование
  - [X] Завести базу со структурой
  - [X] Скрипт тупо наполнения базы
  - [X] Чексуммирование новости и запись чексуммы в базу
* DONE Постоянное выкачивание, автоматизированная работа, деплой куда-нибудь на хероу
* DONE Проверка чексуммы при повторном скачивании
* DONE Добавить дату и ссылку в выдачу отредактированных новостей
* DONE Добавь Спутник.КГ! http://ru.sputnik.kg/export/rss2/archive/index.xml
* TODO [0/4]  Сделай экстеншин для браузера: открываешь новость, а там показано сколько раз редактировалось, кнопки просмотра версий и сравнения
  - [ ] [0/5] MVP: отображай просто факт того, что заголовок был изменён
    - [ ] Веб-сервер и публичный эндпойнт, возвращающий диффы/хэшсуммы по url'у либо guid'у новости (Эликсир?)
    - [ ] Дай экстеншину пермишин на просмотр контента, но только сайтов тех агенств, которые мы отслеживаем
    - [ ] Экстеншин должен научиться определять, что он на отслеживаемом агенстве и внутри новости
    - [ ] Экстеншин должен посылать http(s)-запрос на сервак, передав либо guid либо url новости
    - [ ] Экстеншин должен менять код страницы, вставляя инфу о том, что заголовок был отредактирован
  - [ ] Сделай чтобы можно было раскрыть историю изменения заголовка с красочными диффами (https://github.com/kpdecker/jsdiff в помощь)
  - [ ] Пусть иконка эксиеншина загорается цветом (вместо обычного серого), если было редактирование. И пусть число редактирований показывает.
  - [ ] Обходи блокировку агенств: пусть экстеншин сверяет хэш и сам отправляет контент  на сервер, если контент не совпадает. Хер такое заблокируешь.
* Судя как минимум по одной новости во время выборов, количества редактирований пипец велико даже если смотрет раз в 10 минут. Надо ставить раз в минуту, там самое интересное! Пример:
Новость 23953 из агенства Zanoza от [11/12 10:04] http://zanoza.kg/doc/349029_zaderjan_kandidat_v_depytaty_ot_raj._iakoby_za_podkyp_izbirateley.html
[11/12 10:11] Задержан кандидат в депутаты от РАЖ. Якобы  за подкуп избирателей
[11/12 10:31] Задержан кандидат в депутаты. Якобы  за за подкуп избирателей
[11/12 10:41] ЗадержанВ Кемине задержан кандидат в депутаты. Якобы за подкуп избирателей
[11/12 11:51] В Кемине задержан кандидатагитатор в депутатыРАЖ. Якобы за подкуп избирателей
[11/12 12:09] В Кемине задержан агитаторпредставитель РАЖ. Якобы за подкуп избирателей
[11/12 12:31] В Кемине задержан представитель РАЖпартии. Якобы за подкуп избирателей
* [0/2] Запили криптографическое доказательство редактирования новостей
  - [ ] Прикрути TLSNotary для тех, у кого работает HTTPS (неопровержимость контента)
  - [ ] Помещай все чексуммы в блокчейн (неопровержимость таймстемпа)
* Показывай диффы в самом тексте новосте, авторе и других полях
* Найти кто бесплатно сервачок и базу даст
* Выяснить про интеллектуальную собственность. Чтобы не подкопались даже.
