development:
  adapter: sqlite3
  database: <%= File.join(ROOT_DIRECTORY, '../data/development.sqlite3') %>
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] %>
